name: oggm-simulator
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.6
  - jupyter
  - bokeh
  - nbserverproxy
  - tornado<6
  - ipywidgets
  - graphviz
  - numpy<1.17
  - scipy
  - pandas
  - shapely
  - netcdf4
  - configobj
  - xarray
  - pyviz_comms
  - param
  - holoviews
  - hvplot
  - panel
  - parambokeh
  - ipympl
  - pip:
    - joblib
    - progressbar2
    - git+https://github.com/OGGM/oggm.git
    - jupyter-panel-proxy
